# This file uses to set up dev database. Needed for Developing purpose
version: '3'

services:
    db:
        image: postgres:13-alpine
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=atom
            - POSTGRES_USER=atom
            - POSTGRES_PASSWORD=atom
        networks:
            - web

    python:
        build:
            context: ./
            dockerfile: ./deploy/python/Dockerfile
        restart: always
        env_file:
            - .env
        ports:
            - 80:8000
        environment:
            - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME:-atom}
            - POSTGRES_USER=${POSTGRES_USER:-atom}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-atom}
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - DEBUG=${DEBUG:-True}
        depends_on:
            - db
        networks:
            - web

networks:
    web:
        external:
            name: web

volumes:
    db:
