# Generated by Django 3.2.6 on 2021-08-29 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_period_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone number. Contains region, and number itself'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time_actual',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
