# Generated by Django 3.2.6 on 2021-08-28 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='vector_name',
        ),
        migrations.AddField(
            model_name='action',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='keywords_vectorized',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default='{}', size=None),
            preserve_default=False,
        ),
    ]
