# Generated by Django 3.2.6 on 2021-08-28 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210828_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='keywords_vectorized',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None),
        ),
    ]
