# Generated by Django 3.2.6 on 2021-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210829_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
