# Generated by Django 3.2.6 on 2021-08-29 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
